{{- if .Values.core.enabled -}}
{{- $component := "core" -}}
{{- $ctx := dict "context" . "component" $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goat.serviceFullname" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" $ctx | nindent 4 }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      {{- include "goat.serviceSelectorLabels" $ctx | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        {{- include "goat.serviceSelectorLabels" $ctx | nindent 8 }}
        {{- with .Values.core.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.core.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: core
          image: {{ include "goat.image" (dict "image" .Values.core.image "global" .Values.global "root" $) }}
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          {{- with .Values.core.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "goat.serviceFullname" $ctx }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "goat.postgresql.secretName" . }}
                  key: {{ include "goat.postgresql.userKey" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "goat.postgresql.secretName" . }}
                  key: {{ include "goat.postgresql.passwordKey" . }}
            {{- with .Values.core.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.core.livenessProbe.enabled }}
          livenessProbe:
            {{- $lp := omit .Values.core.livenessProbe "enabled" }}
            {{- toYaml $lp | nindent 12 }}
          {{- end }}
          {{- if .Values.core.readinessProbe.enabled }}
          readinessProbe:
            {{- $rp := omit .Values.core.readinessProbe "enabled" }}
            {{- toYaml $rp | nindent 12 }}
          {{- end }}
          {{- with .Values.core.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
