{{- if .Values.core.enabled -}}
{{- $component := "core" -}}
{{- $ctx := dict "context" . "component" $component -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goat.serviceFullname" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" $ctx | nindent 4 }}
  {{- with .Values.core.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "goat.serviceSelectorLabels" $ctx | nindent 4 }}
{{- end }}
