{{- if and .Values.catalog.enabled .Values.catalog.ingress.enabled -}}
{{- $component := "catalog" -}}
{{- $ctx := dict "context" . "component" $component -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goat.serviceFullname" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" $ctx | nindent 4 }}
  {{- with .Values.catalog.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.catalog.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.catalog.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.catalog.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "goat.serviceFullname" $ctx }}
                port:
                  number: {{ $.Values.catalog.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
