{{- if .Values.windmill.workers.workflows.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goat.serviceFullname" (dict "context" . "component" "windmill-worker-workflows") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" (dict "context" . "component" "windmill-worker-workflows") | nindent 4 }}
data:
  {{- range $k, $v := .Values.windmill.workers.workflows.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
