{{- if .Values.geoapi.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goat.serviceFullname" (dict "context" . "component" "geoapi") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" (dict "context" . "component" "geoapi") | nindent 4 }}
data:
  {{- range $k, $v := .Values.geoapi.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  POSTGRES_SERVER: {{ include "goat.postgresql.host" $ | quote }}
  POSTGRES_DB: {{ include "goat.postgresql.database" $ | quote }}
  POSTGRES_PORT: {{ include "goat.postgresql.port" $ | quote }}
{{- end }}
